### PR TITLE
Fix diff lexer highlighting of deleted lines.

### PR DESCRIPTION
**Pull request by DouweM**
Deleted lines were no longer highlighted properly :(

screen shot 2015-07-30 at 13 59 29

The tokens now match those of Rugments: https://bitbucket.org/birkenfeld/pygments-main/src/1835fdd773a43477c51d5d4242ffee03e65aa15a/pygments/lexers/diff.py?at=default 

cc @rumpelsepp

### CODE REVIEW

**Comment by rumpelsepp** [comment]
Did you check if this still works for email patches? 

```patch
From 5107e733daec222b3ae828ead05f630de425f451 Mon Sep 17 00:00:00 2001
From: Douwe Maan <douwe@selenight.nl>
Date: Thu, 30 Jul 2015 13:58:38 +0200
Subject: [PATCH] Fix diff lexer.

---
 lib/rouge/lexers/diff.rb | 8 ++------
 1 file changed, 2 insertions(+), 6 deletions(-)

diff --git a/lib/rouge/lexers/diff.rb b/lib/rouge/lexers/diff.rb
index 3c2a598..881e2f2 100644
--- a/lib/rouge/lexers/diff.rb
+++ b/lib/rouge/lexers/diff.rb
@@ -12,17 +12,13 @@ class Diff < RegexLexer
       def self.analyze_text(text)
         return 1   if text.start_with?('Index: ')
         return 1   if text.start_with?('diff ')
-
-        # TODO: Have a look at pygments here, seems better
-        return 0.9 if text =~ /\A---.*?\n\+\+\+/m
+        return 0.9 if text.start_with?('--- ')
       end
 
       state :root do
         rule(/^ .*\n/, Text)
         rule(/^\+.*\n/, Generic::Inserted)
-        # Do not highlight the delimiter line
-        # before the diffstat in email patches.
-        rule(/^-+ .*\n/, Generic::Deleted)
+        rule(/^-+.*\n/, Generic::Deleted)
         rule(/^!.*\n/, Generic::Strong)
         rule(/^@.*\n/, Generic::Subheading)
         rule(/^([Ii]ndex|diff).*\n/, Generic::Heading)
```

The first delimiter `---` line must not be highlighted.

**Comment by DouweM** [comment]
@rumpelsepp It didn't, it does now :)

**Comment by DouweM** [comment]
@jneen Would you happen to have time to review this patch? This solves an issue we were having in GitLab.

**Comment by supernova32** [comment]
ping @jneen

**Comment by Razer6** [comment]
@jneen Can you take a look on that PR?

**Comment by jneen** [comment]
Whoops, forgot to merge this one.

**Comment by jneen** [comment]
Released in v1.10.1.

**Comment by Razer6** [comment]
Awesome :heart:

**Comment by stanhu** [comment]
Thanks again, @jneen! rouge v1.10.1 will be shipping with GitLab 8.0.

**Comment by jneen** [comment]
<3

**Comment by dosire** [comment]
Thanks for the merge!

**Pull request merged**
