### PR TITLE
Add lexer for the Interactive Data Language (IDL)

### PR DESCRIPTION
**Pull request by sappjw**
This lexer was started off of the Fortran lexer due to their similarities, so I modified its sample code to work with the latest version of IDL.  This is my first attempt, so some of the highlighting types may be wrong.

See the [IDL web site](http://www.exelisvis.com/IntelliEarthSolutions/GeospatialProducts/IDL.aspx) for more information on the language.

### CODE REVIEW

**Comment by sappjw** [comment]
The file extension ".pro" conflicts with the prolog lexer, but I'm not sure how best to address this.

**Comment by jneen** [comment]
Hm, okay, I'm gonna have to do some work on the guessing infra, since it's mostly broken right now (o_o). For now, can you remove the `.pro` extension? I'd like to keep it associated with prolog until we figure out a better way to handle ambiguity in guessing.

**Comment by sappjw** [comment]
Sure, that makes sense...this limits impact to existing code.  However, the .pro extension is what is searched for by the IDL program when compiling scripts in its path so it would be good to eventually work out the file type guessing.

**Comment by malteger** [comment]
Is it possible to merge this state of the highlighter and add the pro extension in an follow up pull request? Or is it possible to add the pro extension with the updated guesser code, so this is completed?
In my working group there is a lot of IDL code and therefore a demand for highlighting this.

**Pull request merged**
