### PR TITLE
Use require instead of load to handle double loading

### LINKED ISSUE #290: Modules already initialized bug
I am experiencing a bug with `1.9.1` with some console output in the Travis log in one of my [repos](https://travis-ci.org/rodrigoargumedo/personal-website-rails):

```ruby
/home/travis/build/rodrigoargumedo/personal-website-rails/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: already initialized constant Rouge::Lexers::Shell::KEYWORDS
/home/travis/build/rodrigoargumedo/personal-website-rails/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:20: warning: previous definition of KEYWORDS was here
/home/travis/build/rodrigoargumedo/personal-website-rails/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: already initialized constant Rouge::Lexers::Shell::BUILTINS
/home/travis/build/rodrigoargumedo/personal-website-rails/vendor/bundle/ruby/2.1.0/gems/rouge-1.9.1/lib/rouge/lexers/shell.rb:25: warning: previous definition of BUILTINS was here
```

I did confirm that this bug is already on development and testing environment with Rails. It seems a bit strange to get this particular warnings about already initialized `Rouge::` constant modules.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #290.

The bug was caused by Powershell being loaded before Shell, which is exactly what `$LOADED_FEATURES` was designed to solve.

### CODE REVIEW

**Comment by elstgav** [comment]
:+1: hope this gets merged soon!

**Comment by Arcovion** [comment]
Can also use `require_relative`:
```ruby
require_relative 'rouge/lexer'
require_relative 'rouge/regex_lexer'
require_relative 'rouge/template_lexer'

Dir.glob 'rouge/lexers/*.rb', &method(:require_relative)
```

**Comment by segiddins** [comment]
@Arcovion iirc `require_relative` was only added in 2.0?

**Comment by Arcovion** [comment]
It was added in `1.9.2`: http://ruby-doc.org/core-1.9.2/Kernel.html#method-i-require_relative

**Comment by calebhailey** [comment]
:+1: seeing this too & looking forward to seeing this merged. :)

**Comment by stanhu** [comment]
You might want to look at #298; I did it before realizing this PR was here. It eliminates all `load` calls and also allows `rackup` to work properly.

**Comment by jneen** [comment]
I ended up doing this a different way. If rackup continues to not work properly, we can deal with that when we get there.

**Pull request closed without merging**
