### PR TITLE
add ActionScript 3 lexer

### PR DESCRIPTION
**Pull request by honzabrecka**
I really miss this language.

### CODE REVIEW

**Comment by jneen** [comment]
Cool, it'd be good to have an actionscript lexer :).  A couple things I'd ask before merging:

* Create a test file at `spec/visual/samples/actionscript` that contains some basic tests, and whatever edge cases you want to catch (pygments might have a good test file you could copy)
* Make sure all files end in newlines
* Make sure the specs pass (run `rake`)

Thanks a ton!

**Comment by honzabrecka** [comment]
I made required changes, but I'm not sure if it's ok, so please do a code review. I'm not familiar with ruby, but I can help with any ActionScript code. :)

**Comment by honzabrecka** [comment]
Is it OK or should I improve something? :)

**Comment by honzabrecka** [comment]
Any chance?

**Comment by mnordine** [comment]
Forgive me, but I'm new to pull requests on github. I can't figure out why this issue was closed. Was it just closed without any reason?

**Comment by jneen** [comment]
Looks like it.

**Comment by BenV** [comment]
It would be great to get this merged, as our AS3 code no longer gets highlighted on GitHub Pages 😦

**Pull request merged**
