### PR TITLE
Add typescript react (tsx) lexer

### PR DESCRIPTION
**Pull request by hwdegroot**
Basically this is combining `typescript` and `JSX` lexers

### CODE REVIEW

**Comment by jneen** [comment]
Hi! This looks like a copy-and-paste job from the JSX lexer. Could you find a different way to do it? Thanks!

**Comment by Kovensky** [comment]
@jneen The problem isn't that this needs to inherit both from the JSX lexer _and_ the TypeScript lexer. Copying the (far smaller) JSX lexer seems like the lesser evil, unless it's possible to do multiple inheritance.

**Comment by hwdegroot** [comment]
Indeed it is a copy-paste. But I choose to copy paste the least complex one. In the end it is just a mix of typescript and jsx

**Comment by jneen** [comment]
It should be possible to abstract out a module like SCSS / SASS do, which would be far easier to maintain than a copy-pasted lexer.

**Comment by jneen** [comment]
Or use a common subclass and swap out a `parent_lexer` definition in the base.

**Comment by hwdegroot** [comment]
I agree that it is not the best. Will look into this.

**Comment by jneen** [comment]
Closed in favor of #669.

**Pull request closed without merging**
