### PR TITLE
Display help when using rougify with no args

### PR DESCRIPTION
**Pull request by BigChief45**
Rougify strangely hangs when using `rougify` without any arguments.

This issue might also be related: #688

### CODE REVIEW

**Comment by dblessing** [comment]
@BigChief45 Thanks. Do you mind adding a quick spec? You can add it to `spec/cli_spec.rb`

**Comment by BigChief45** [comment]
@dblessing No problem

I have added the spec. Not sure if `'nil'` would be an appropriate description for it. Please let me know.

**Comment by dblessing** [comment]
Looks good to me. I restarted a failing build - it looks like a transient failure. If it passes, I'll merge.

**Comment by BigChief45** [comment]
@dblessing Seems good to merge now.

**Comment by dblessing** [comment]
Thanks @BigChief45

**Pull request merged**
