### PR TITLE
Prometheus

### PR DESCRIPTION
**Pull request by dblessing**
A WIP lexer for Prometheus query lang. It's a quick hack and my first lexer. 

A `Terminal256` preview based on the demo:

screen shot 2016-08-19 at 2 34 18 pm

As you can see, I could use some recommendations on better tokens 😄

### CODE REVIEW

**Comment by dblessing** [comment]
I'm using https://prometheus.io/docs/querying/basics/ as a guide.

**Comment by dblessing** [comment]
@jneen Ready for final review.

**Comment by jneen** [comment]
@dblessing looks like you haven't pushed?

**Comment by dblessing** [comment]
🙌  ✅

**Pull request merged**
