### PR TITLE
Few fixes and improvements to Apache lexer

### PR DESCRIPTION
**Pull request by julp**
* faster keyword lookups
* no nil error on unknown directive (`lib/rouge/lexer.rb:392:in `block in lex': undefined method `<<' for nil:NilClass (NoMethodError)`) (cf issues #246, #300 )
* directive and section names are case insensitive according to Apache's documentation (also reported by issue #246)
* handle Windows end of line (CR+LF vs LF) (entire document appears as Error)

### CODE REVIEW

**Comment by jneen** [comment]
Hi! This looks good. Unfortunately `Array#bsearch` isn't supported in ruby 1.9, which rouge still supports.  Perhaps you could load the yaml file into a set or a hash instead?

**Comment by julp** [comment]
Hi,

is it ok with a conditionnal class method defined in Lexer? That way:
* Array class isn't polluted
* it can be reused by any lexer
* the test on availability of Array#bsearch is only done once
* for Ruby >= 2.0, we benefit of bsearch "speed" (larger is the array, faster is the search)

**Comment by jneen** [comment]
Is it possible to just use a Set instead of an Array?

**Comment by julp** [comment]
Because Set internaly uses a Hash? Indeed, it makes sense.

Cleaned up (but I kept initial YAML file approach).

**Comment by jneen** [comment]
Wonderful, thanks!

**Comment by jneen** [comment]
Released in v1.11.0.

**Pull request merged**
