### PR TITLE
add a CMake lexer

### PR DESCRIPTION
**Pull request by julp**
Proposal for CMake

### CODE REVIEW

**Comment by jneen** [comment]
Looks good, same issue as the Apache PR - if you can find a way to do it without `Array#bsearch` that'd be awesome.

**Comment by julp** [comment]
Updated too ;)

**Comment by jneen** [comment]
Awesome, great work!

Last thing is it looks like there's a bug in the string state.  When I open the visual spec (`rackup` and `localhost:9292/cmake`), I see this:

cmake

If I'm interpreting the text right, it looks like that string section is ending early.

**Comment by julp** [comment]
I'm confused: the `- 1` should not be here. For comments, we deduce the beginning '#' character but for strings, which start immediately by a relevant square bracket, there is nothing to do.

I've also forgotten to add brackets in the regexp for one line comments when I replaced `\R`.

**Pull request merged**
