### PR TITLE
GraphQL: Support for multiline strings

### LINKED ISSUE #992: GraphQL multiline strings
Looks like multiline strings are not supported.
They are often used for descriptions. In this case highlighted code is much worse readable than plain text

for example code like this:

```graphql
"""
Decimal number serialized as string.

Should match regexp: `/^[+-]?[0-9]+(\.[0-9]+)$/`

Format:
  `<sign>`? `<digit>`+ ( `.` `<digit>`+ )?

Example:
 - `"1000"`
 - `"0.00000001"`
 - `"-10"`
 - `"+1"`

This is invalid:
 - `".01"` *missing preceding zero*
 - `"1,000.00"` *invalid character*
 - `"1e-10"` *exponential form is not allowed*
"""
scalar Decimal

```

### LINKED ISSUE #993: GraphQL: Markdown descriptions
This depends on #992 

But question is if inline descriptions can be Markdown hiqhlighted, for exampl same code as in #992:

```graphql
"""
Decimal number serialized as string.

Should match regexp: `/^[+-]?[0-9]+(\.[0-9]+)$/`

Format:
  `<sign>`? `<digit>`+ ( `.` `<digit>`+ )?

Example:
 - `"1000"`
 - `"0.00000001"`
 - `"-10"`
 - `"+1"`

This is invalid:
 - `".01"` *missing preceding zero*
 - `"1,000.00"` *invalid character*
 - `"1e-10"` *exponential form is not allowed*
"""
scalar Decimal
```

may be rendered similar to this:

```graphql
"""
```
> ### Decimal number serialized as string.
> 
> Should match regexp: `/^[+-]?[0-9]+(\.[0-9]+)$/`
> 
> Format:
>   `<sign>`? `<digit>`+ ( `.` `<digit>`+ )?
> 
> Example:
>  - `"1000"`
>  - `"0.00000001"`
>  - `"-10"`
>  - `"+1"`
> 
> This is invalid:
>  - `".01"` *missing preceding zero*
>  - `"1,000.00"` *invalid character*
>  - `"1e-10"` *exponential form is not allowed*
```graphql
"""
scalar Decimal
```

### PR DESCRIPTION
**Pull request by dblessing**
Fixes #992 and fixes #993

Adds support for multiline strings for GraphQL and markdown descriptions. 

Markdown descriptions are in the GraphQL spec at https://facebook.github.io/graphql/draft/#sec-Descriptions

### CODE REVIEW

**Comment by dblessing** [comment]
@langpavel What do you think of this? It adds support for regular multiline string values, plus markdown descriptions.

One note that differs from your example in #993. The first line is not made into a markdown header in this case. That's because the GraphQL lexer simply delegates the text to the Markdown lexer, which would only make the first line a header if it was preceded by some form of `#`. 

Is this acceptable? If this is a surprise for GraphQL users we could potentially inject a preceding `#`. Although, that would be slightly unprecedented in Rouge, I think.

**Comment by langpavel** [comment]
@dblessing Hi, thank you for your effort!

I think that first line can be treated as you did, so it will not break reading so much.
`<h1>` is often too big and results may be horrible if you inject `#` implicitly.

It's perfectly fine to left first paragraph as is, you can see that other tooling like `graphiql` and `prisma` interprets first line as plain paragraph...

**Comment by dblessing** [comment]
@langpavel Perfect! I'll take this as-is, then.

If you're familiar with GraphQL and multiline strings, would you mind checking that my second example in the samples file is valid? From looking at the multiline spec, I believe it is but I have little real-world experience on GraphQL.

**Comment by langpavel** [comment]
I'm just curious: what `Str::Double` is? I'm newbie in ruby :-)

**Comment by langpavel** [comment]
> If you're familiar with GraphQL and multiline strings, would you mind checking that my second example in the samples file is valid? From looking at the multiline spec, I believe it is but I have little real-world experience on GraphQL.

Of course.. I will edit this, give me a second

**Comment by langpavel** [comment]
Thank you @dblessing! I will be very satisfied if this lands soon! :-)

**Comment by dblessing** [comment]
Thanks @langpavel

**Comment by langpavel** [comment]
Can I kindly ask you when you plan new release? @dblessing @jneen :pray:

**Pull request merged**
