### PR TITLE
add digdag syntax (*.dig)

### PR DESCRIPTION
**Pull request by gfx**
Added digdag support. This is almost the same as YAML, but unlike YAML, the order of keys matters, so I have introduced a new lexer.

* https://www.digdag.io/ - a simple workflow engine developed by @treasure-data
* example files: https://github.com/treasure-data/digdag/tree/master/examples

### CODE REVIEW

**Comment by jneen** [comment]
Can you not just associate `*.dig` with yaml? you don't add any new rules here...

**Comment by gfx** [comment]
The syntax of `*.digdag` is almost the same as YAML, but there are some reserved words, e.g. `timezone`, `for_each`, and `_do`, and so on.

For now, I just need the syntax highlight but in a future,  I (or digdag contributors) will add them.

**Comment by gfx** [comment]
Should I add the reserved words in this PR?

**Comment by jneen** [comment]
Ah, yes, if that would be possible. The YAML lexer is... complicated. But let's have a whole implementation before we merge it.

**Comment by gfx** [comment]
Added keywords to digdag lexer: b6d8b426dbb8c7652dd555ed9bea97c62727bdb1

This is like:

screen shot 2017-06-03 at 15 15 11

**Comment by gfx** [comment]
Thank you!

**Pull request merged**
