### PR TITLE
Ceylon lexer

### PR DESCRIPTION
**Pull request by bjansen**
This PR adds a lexer for the [Ceylon programming language](http://ceylon-lang.org).

### CODE REVIEW

**Comment by jjatria** [comment]
I think the demo and the visual sample should be the other way around: the demo is the short snippet of code that will be displayed in the [Rouge website](http://rouge.jneen.net/) (and on the landing page of the server when started with `rackup`), while the visual sample is supposed to be a more extensive example where you can make sure that all edge cases are correctly lexed.

I'd swap the demo and the sample in your commit.

**Comment by bjansen** [comment]
I thought the example shown in `rackup` was different from the one shown on the website, but I might be wrong. How can I test the visual sample then? I didn't find any command that generates the highlighted version of this sample.

**Comment by jjatria** [comment]
From the readme:

> To test a lexer visually, run `rackup` from the
> root and go to `localhost:9292/#{some_lexer}`
> where `some_lexer` is the tag or an alias of a
> lexer you'd like to test. If you add `?debug=1`,
> helpful debugging info will be printed on stdout.

That debug option, by the way, is a life saver.

**Comment by bjansen** [comment]
Yes, that's what I used to check my lexer, but it's showing the "long" sample in the "demos" folder, not the one in spec/visual/samples. I don't know what this second file is used for.

**Comment by jjatria** [comment]
When you start the server with `rackup` and go to `localhost:9292`, the snippets that are shown on that page are the ones in the `lib/rouge/demos` directory. `localhost:9292/some-lexer` _should_ show the ones in `spec/visual/samples`. Is this not what you see?

**Comment by bjansen** [comment]
Oh you're totally right, sorry, I was mixing `localhost:9292/#ceylon` with `localhost:9292/ceylon`. I'll swap the two samples right now. Thanks!

**Comment by jjatria** [comment]
No problem!

I guess that hash in the readme _is_ a bit misleading. Maybe it should be removed, @jneen?

**Comment by jneen** [comment]
Hi @bjansen! This looks awesome! Just one thing before I merge - could you make sure your ruby files all use 2-space indentation? Otherwise this looks good.

**Comment by bjansen** [comment]
Hi @jneen! I just updated the PR, I hope everything's correct now.

**Comment by jneen** [comment]
Thanks!

**Comment by jneen** [comment]
Released in v1.11.0.

**Comment by bjansen** [comment]
Great, thank you very much!

**Pull request merged**
