### PR TITLE
Create lexer for the Pascal programming language

### PR DESCRIPTION
**Pull request by alexcu**
Added rules for a basic Pascal lexer. It does a reasonable job of
highlighting Pascal code. There is a bit of room for improvement
such as adding support for the different 'flavours' of Pascal i.e.
Free Pascal, Turbo Pascal etc. A Delphi lexer can easily be extended
from this lexer, however due to my lack of experience with Delphi I
chose not to include this in.

### CODE REVIEW

**Comment by lukasmesicek** [comment]
Nice work, very useful :+1: 

There are some missing other keywords.

```default  
exit  
message
nil
on
out
overload
override
pascal
raise
read
register
resourcestring
safecall
stdcall
stored
string
threadvar
```

I look forward to the release :smile:

**Comment by alexcu** [comment]
@lukasmesicek Missing keywords have been added :smile:

**Comment by jneen** [comment]
Hi @alexcu, this looks simple and good. Please make sure all your files end in newlines, and then I will happily merge. Thanks for your work!

**Comment by alexcu** [comment]
Hi @jneen, updated the PR adding in those newlines 😊

**Comment by furai** [comment]
There is one problem with that applied fix. It doesn't take into account all delphi/pascal file extensions.

`*.dpr, *.lpr, *.pp`

These are needed as well.

**Pull request merged**
