### PR TITLE
Add Jinja and Twig lexers

### LINKED ISSUE #188: Add Twig Lexer?
Not sure if the twig template language is as popular as liquid or handlebars, but I'd certainly like it to be added :smile:.

It's already in the [main pygments repo](https://bitbucket.org/birkenfeld/pygments-main/issue/927/missing-lexer-for-twig-language).

Thank you!

### PR DESCRIPTION
**Pull request by robin850**
Hello !

That's just a tiny pull request that implements a Jinja lexer and a Twig lexer that inherits from the former but defines its own keywords, etc.

Let me know if I'm doing something wrong, I'm not that comfortable with regular expressions.

Closes #188.

Have a nice day and keep up the goodwork on this library !

### CODE REVIEW

**Comment by fweber-de** [comment]
:+1: thank you, this will benefit me in gitlab ;)

**Comment by glutamatt** [comment]
:+1: too ! reviewers of twig files in gitlab will love it :heart:

**Comment by alexander-schranz** [comment]
:+1:

**Comment by crussell52** [comment]
@jneen This would be a great addition!  Is there anything that we can do to help get this merged/released?

**Comment by miguelbacalhau** [comment]
:+1:

**Comment by pedroresende** [comment]
:+1:

**Comment by fweber-de** [comment]
hey @jneen, thank you for your work with this library :heart: 
can we do something to help you with merging this beneficial PR?

**Comment by alexander-schranz** [comment]
👍

**Comment by tomfun** [comment]
+1

**Comment by jneen** [comment]
Hi @robin850. I would love to support these languages. I'm a little confused as to what the difference is between these and the existing Liquid lexer - could you go over the differences?

**Comment by fweber-de** [comment]
Hi, thanks for replying @jneen! :)

liquid and twig seem to share a fair bit of the same syntax, the only difference i can find at a glance is in how liquid handles filters with parameters:

    liquid:
        {{ "/my/fancy/url" | append: ".html" }}
    
    twig:
        {{ "/my/fancy/url"|append(".html") }}

**Comment by jneen** [comment]
Hm, and I'm noticing the liquid lexer does a *lot* more liquid-specific stuff than I first thought. Okay, I think eventually we should consolidate these somehow, but that's for another time.

Thanks for the pull request!

**Comment by robin850** [comment]
Thanks @jneen ! :heart:

**Comment by fweber-de** [comment]
Thank you @jneen ❤️

**Comment by jneen** [comment]
Released in v1.11.0.

**Pull request merged**
