### PR TITLE
Adding PowerShell builtin commands for version 5

### PR DESCRIPTION
**Pull request by JacodeWeerd**
I only know PowerShell and do not know anything about Ruby and I hope this commit is correct.
If I made a mistake, please let me know.

I used the following script to get the PowerShell 5 commands:

```powershell
$PowerShellNativeModules = Get-Module -ListAvailable | where {$_.ModuleBase -like "C:\windows\system32\WindowsPowerShell\v1.0\Modules\*"} | where {$_.Author -eq "Microsoft Corporation"}
$ModuleNames = $PowerShellNativeModules | select -ExpandProperty name
$NativeCommands = Get-Command -Module $ModuleNames | select -ExpandProperty name
$NativeAliases = Get-alias | where {$_.Module -eq $null} | select -ExpandProperty name

$AllNativeCommands = $NativeCommands + $NativeAliases

$MaxWidth = 80
$Width = 0
[string[]]$Text = $null
[string]$Line = $null
foreach ($Word in $AllNativeCommands ){
    $Width += $word.Length + 1
    if ($Width -gt $MaxWidth ){
        $Text += $Line
        $Width = $word.Length + 1
        $Line = $Word + " "
    }
    Else{
        $Line = $Line + $Word + " "
    }
}
#Add remaining piece of line
If ($Line) {
    $Text += $Line
}

$Text | Out-File -FilePath $env:TEMP\commands.txt -Encoding utf8
start $env:TEMP\commands.txt
```

### CODE REVIEW

**Comment by JacodeWeerd** [comment]
Nice to hear, thanks!

Any idea when the request could be merged? (Only nice to know, not in a hurry 😉   )

**Comment by aaroneg** [comment]
I have no control on that front, that's a question for @jneen

**Comment by gfx** [comment]
Excellent. Thanks for the contribution!

**Comment by JacodeWeerd** [comment]
Glad I could help!

**Pull request merged**
