### PR TITLE
Rust: recognize range operator and type variables

### PR DESCRIPTION
**Pull request by whitequark**
Right now they get highlighted as errors.

### CODE REVIEW

**Comment by jneen** [comment]
Awesome, thanks! Could you add some code samples to `spec/visual/samples/rust` that use this syntax?

**Comment by whitequark** [comment]
@jneen Done, and cleaned up a bit too.

**Comment by jneen** [comment]
Awesome, thanks!

**Comment by whitequark** [comment]
Thanks for the quick merge as well.

**Pull request merged**
