### PR TITLE
Fix #835: Haskell quasiquotations

### LINKED ISSUE #835: Quasiquotations in Haskell are highlighted incorrectly
Rouge appears to treat the contents of quasiquotations as regular Haskell expressions. [Here's an example](http://rouge.jneen.net/pastes/bQxq). The meaning of everything between `[somequasiqouter|` and `|]` is determined entirely by `somequasiquoter`, so highlighting as though it were Haskell is incorrect. The syntax is `[quoter| string |]` i.e. a `[`, a name, and a string not including the sequence `|]` followed by the sequence `|]`.

The relevant documentation is [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#template-haskell-quasi-quotation).

### PR DESCRIPTION
**Pull request by enolan**
I got quasiquotations to work :)

### CODE REVIEW

**Comment by miparnisari** [comment]
Shouldn't you add tests for this?

**Comment by enolan** [comment]
I mean, ideally yes, but there are any tests for the Haskell lexer in
general. Just the filetype guessing

**Comment by miparnisari** [comment]
Sorry, i wasn't clear. I meant adding the quasiquotations to the demo file.

**Comment by enolan** [comment]
Oh, OK that's reasonable

**Pull request merged**
