### PR TITLE
Fix javascript colons... again

### LINKED ISSUE #459: Javascript highlight error if object property is quoted
When using javascript syntax highlighting, if you define an object with a quoted property name _and_ the value is an object, the next property is highlighted as an error.

Screenshot of highlighting error

If the property name is not quoted, or the value is not an object, it's fine.

http://rouge.jneen.net/pastes/K3OA

### PR DESCRIPTION
**Pull request by jneen**
If successful, fixes #459.

### CODE REVIEW

**Comment by jneen** [comment]
@yuloh, @nbering, could you check and see if this patch fixes your issue?

**Comment by nbering** [comment]
@jneen I can give it a go if I can figure out how. Is there a way I can use bundler or something to override the version used by the github-pages gem for jekyll? Checking out PR branches is a solved problem for me, but I'm more of a JavaScript developer and only understand the ruby ecosystem at a higher level. Willing to try to help though. Below is my gemfile. I copied it from documentation somewhere.

```
source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages'], group: :jekyll_plugins
gem 'jekyll-redirect-from'
```

**Comment by nbering** [comment]
I couldn't get it to work in jekyll because bundler doesn't appear to allow version overrides. I ran rougify with the old version and this version and the output on the command line looks good. The old version also successfully reproduced the issue with rougify so I think this is fixed for my case anyway.

**Comment by yuloh** [comment]
Works great for me 👍

**Pull request merged**
