### PR TITLE
Swift 2 changes

### PR DESCRIPTION
**Pull request by radex**
- added support for the new keywords
- `try!` operator
- `#available(...)` macro
- simplified `@attribute`s — their syntax is unambiguous in Swift, so there's no reason to check for particular attributes, and this way is more future-proof…

### CODE REVIEW

**Comment by jneen** [comment]
Hey sorry it took me so long to get to this. It looks good thanks :]

**Comment by jneen** [comment]
(i do like the change for the `@`-prefixed annotations - it's a lot simpler to highlight this way!)

**Comment by radex** [comment]
Thank you!

**Comment by jneen** [comment]
Released in v1.10.0.

**Pull request merged**
