### PR TITLE
D lexer

### LINKED ISSUE #24: Implement a D lexer

### PR DESCRIPTION
**Pull request by nikibobi**
I have created a D lexer that is very similar to the [pygments one](https://bitbucket.org/birkenfeld/pygments-main/src/859b2bce647cd212e39cd63f83f93f4083b232b2/pygments/lexers/d.py)
I will add demo for D later. This should close #24 after I get a review

### CODE REVIEW

**Comment by wilzbach** [comment]
@jneen - please have a look. D is starting to get a popular language :)

**Comment by jneen** [comment]
Hi @nikibobi, this looks great! Would you mind fixing the indentation to use 2 spaces before I merge this?

**Comment by nikibobi** [comment]
@jneen ok I fixed it

**Comment by jneen** [comment]
Thanks!

**Comment by jneen** [comment]
Released in v1.11.0.

**Pull request merged**
