### PR TITLE
Added GLSL lexer

### PR DESCRIPTION
**Pull request by sriharshachilakapati**
I have required a GLSL lexer so I wrote one myself. This one is complete, with all the keywords, data types and the built-ins.

Here is a preview.

### CODE REVIEW

**Comment by jneen** [comment]
Hi there - thanks for the lexer!  I notice it's almost exactly the same as the C lexer - do you think you could subclass it instead and use the `prepend` / `append` interface? (like the C++ or Objective C lexers)

**Comment by jneen** [comment]
Also to get the specs top pass, you need to add a visual spec (`spec/visual/samples/glsl`) that hits most of the edge cases you can think of, and a demo (`lib/rouge/demos/glsl`) that shows off the basic functionality.

**Comment by sriharshachilakapati** [comment]
I'll take a look at that. Thanks for the information. I'll add the samples and the test cases in the next commit.

**Comment by sriharshachilakapati** [comment]
I have made the GLSL lexer extend the C lexer, and also added the samples and test cases. I think everything is fine now.

**Comment by jneen** [comment]
Wonderful, looks great!

**Pull request merged**
